<tr class="border-b border-gray-200 dark:border-gray-700">
    <x-td>
        <p class="font-bold">Reference #: {{ $data->reference_number }}</p>
        <p class="text-xs mt-1 font-semi">Generated By: {{ $data->modified_by }}</p>
        <p class="text-xs mt-1 font-semi">Date and time: {{ $data->updated_at }}</p>
    </x-td>
    <td class="flex flex-row justify-center">
        <x-action-dropdown :id="$data->id" class="mt-8">
            <x-action-dropdown-item label="View" type="button" wire:click="show()" />
        </x-action-dropdown>
    </td>
</tr>
