<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Fc007Log extends Model
{
    use HasFactory;
    protected $fillable = [
        'reference_number', 'file_path', 'modified_by', 'hash', 'status_id', 'generated_by',
        'verified_by', 'verified_at', 'approved_by', 'approved_at', 'send_back_details',
        'send_back_at', 'send_back_by', 'principal_id', 'payment_slip_by', 'payment_slip_at',
        'or_by', 'or_at'
    ];

    protected static function boot()
    {
        parent::boot();
        static::creating(function ($model) {
            $fc007 = $model::orderBy('id', 'DESC')->first();
            $hash_id = $fc007 != NULL ? encrypt($fc007->id + 1) : encrypt(1);
            $model->hash = $hash_id;
            $model->modified_by = Auth::user()->full_name;
        });

        static::updating(function ($model) {
            $model->modified_by = Auth::user()->full_name;
        });
    }

    // relationship
    public function principal()
    {
        return $this->belongsTo(Company::class, 'principal_id', 'id');
    }

    // acessor
    public function getAuditLogAttribute()
    {
        switch ($this->status_id) {
            case 2:
                $auditLog = '<p class="text-xs mt-1 font-semi">Generated By: ' . $this->generated_by . ', ' . $this->created_at . '</p>';
                break;
            case 3:
                $auditLog = '<p class="text-xs mt-1 font-semi">Generated By: ' . $this->generated_by . ', ' . $this->created_at . '</p>
                             <p class="text-xs mt-1 font-semi">Verified By: ' . $this->verified_by . ', ' . $this->verified_at . '</p>';
                break;
            case 4:
                $auditLog = '<p class="text-xs mt-1 font-semi">Generated By: ' . $this->generated_by . ', ' . $this->created_at . '</p>
                             <p class="text-xs mt-1 font-semi">Verified By: ' . $this->verified_by . ', ' . $this->verified_at . '</p>
                             <p class="text-xs mt-1 font-semi">Approved By: ' . $this->approved_by . ', ' . $this->approved_at . '</p>';
                break;
            case 5:
                $auditLog = '<p class="text-xs mt-1 font-semi">Generated By: ' . $this->generated_by . ', ' . $this->created_at . '</p>
                             <p class="text-xs mt-1 font-semi">Verified By: ' . $this->verified_by . ', ' . $this->verified_at . '</p>
                             <p class="text-xs mt-1 font-semi">Approved By: ' . $this->approved_by . ', ' . $this->approved_at . '</p>
                             <p class="text-xs mt-1 font-semi">Payment By: ' . $this->payment_slip_by . ', ' . $this->payment_slip_at . '</p>';
                break;
            case 6:
                $auditLog = '<p class="text-xs mt-1 font-semi">Generated By: ' . $this->generated_by . ', ' . $this->created_at . '</p>
                             <p class="text-xs mt-1 font-semi">Verified By: ' . $this->verified_by . ', ' . $this->verified_at . '</p>
                             <p class="text-xs mt-1 font-semi">Approved By: ' . $this->approved_by . ', ' . $this->approved_at . '</p>
                             <p class="text-xs mt-1 font-semi">Payment By: ' . $this->payment_slip_by . ', ' . $this->payment_slip_at . '</p>
                             <p class="text-xs mt-1 font-semi">OR By: ' . $this->or_by . ', ' . $this->or_at . '</p>';
                break;
            default:
                $auditLog = "";
                break;
        }

        return $auditLog;
    }
}
